[package]
name = "http-test"
version = "0.1.0"
authors = ["Florian Schnell <florian.schnell@netlight.com>"]

[dependencies]
actix-web = "0.6.12"
handlebars = "0.32.4"
serde_json = "1.0.19"
serde = "1.0.66"
rand = "0.5.1"